### ISSUE TITLE
weight_list num format

### ISSUE THREAD

**Issue by lfauchon** [yyoulal/spt#2]
Avec un explicit_weight_allocation, le json d'output reecrit sur le weight_list et sort un format etrange.
En input: "weight_list" : [0.4, 0.6],
En output: "weight_list": [..0, ..0]
Le fichier d'output n'est pas repricable.

Pour reproduire:

{

	"req": {
		"object_kind" : "publication",		
		"underlying_list"  : ["bsk"],
		"result": "zzz",
		"today" : 42308,
		"mode" : "simulation"
	},

	"bsk": {
		"object_kind"     : "portfolio",
		"underlying_list" : ["bsk1", "bsk2"],
		"weight_allocation_scheme" : "explicit_weights",
		"start_date" : 42300,
		"calculation_dates": "calc_dates_bsk"
	},

	"calc_dates_bsk": {
		"object_kind": "explicit_dates_generator",
		"date_list": [42300, 42301, 42302, 42303, 42304, 42305, 42306, 42307]
	},

	"explicit_weights": {
		"object_kind" : "explicit_weight_allocation",
		"weight_list" : [0.4, 0.6],
		"underlying_list": ["strat1", "strat2"]
	},

	"strat1" : {
		"object_kind" : "strategy",
		"fixings": "strat1_fixings"
	},

	"strat1_fixings" : {
		"object_kind" : "fixings",
		"date_list" : [42300, 42301, 42302, 42303, 42304, 42305, 42306, 42307],
		"value_list": [101.0,102.0,103.0,104.0,105.0,106.0,107.0,108.0 ]
	},

	"strat2" : {
		"object_kind" : "strategy",
		"fixings": "strat2_fixings"
	},

	"strat2_fixings" : {
		"object_kind" : "fixings",
		"date_list" : [42300, 42301, 42302, 42303, 42304, 42305, 42306, 42307],
		"value_list": [100.0, 101.0,102.0,103.0,104.0,105.0,106.0,107.0]
	}

}

**Comment by yyoulal** [comment]
Thanks.

It is fixed with this commit : 

242af7577ba2a223a75b7f936dea0772bef8a9b5
Fixing a regression in float image routines.
The new code is based on the native Ada.Text_IO.FLoat_IO
package with a bit of additional cleaning (removing leading
spaces and tailing zeros).
